[package]
name = "factorio-achievements-editor"
description = "Minimal parser and editor for Factorio achievements.dat files"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
binrw = "0.15.0"
clap = { version = "4.5.51", features = ["derive"] }
